### ISSUE TITLE
Remove jquery from content-scripts

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdLiPoV2#7]
depending on the number of commands, we can use pure js (if a small number) or perhaps udom (if large)..

**Comment by cqx931** [comment]
ArtAdder is also using q.js(63KB) for promise and ramda(40KB) for dealing with the selector. Do we also want to get rid of them for content script?

**Comment by cqx931** [comment]
https://github.com/dhowe/AdLiPo/pull/11
Removed jquery, ramda.js, q.js from content script

As for the AdLiPo part, I think they should stay at the background instead of injecting into every single content page... If we are going to do that, a simple messaging system between the content script and the background script need to be added.

Maybe we could discuss this in details after you check the current code?

**Comment by dhowe** [comment]
So all the generation stuff (RiMarkov.generateSentences()) should happen in the addon core. All layout stuff should ideally happen in the content-script (CS). So, at a high-level the CS should ask the addon core for each poem with a message, then try to pick the correct font-size based on the DOM element after it is returned. So rita.js and text.js should NOT be in the content-scripts. Instead of calling makeAd() from adlipo-client.js, we call sendMakeAdMessage() instead, which returns a poem. We then select the correct font-size for that poem OR if we cannot find one, send ANOTHER message to the core, asking for a different poem. Layout calculations can be done either with RiTa (as is now the case), or better yet, using the DOM itself...

**Comment by cqx931** [comment]
done
